# Generated by Django 2.1.3 on 2018-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professions',
            field=models.ManyToManyField(blank=True, to='professions.Profession'),
        ),
    ]
