# Generated by Django 2.1.3 on 2018-11-09 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181107_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=11, null=True), blank=True, null=True, size=None),
        ),
    ]
