# Generated by Django 2.1.4 on 2019-01-09 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20190108_1930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rated_user', 'rating_user')},
        ),
    ]
