# Generated by Django 2.1.3 on 2018-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
